"""add portfolio snapshots

Revision ID: cc35ac3f8e16
Revises: fe0848e19929
Create Date: 2026-07-14 14:51:20.386628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc35ac3f8e16'
down_revision: Union[str, Sequence[str], None] = 'fe0848e19929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('snapshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('security_id', sa.String(length=16), nullable=True),
    sa.Column('portfolio_name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('portfolio_weight', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('source_sheet', sa.String(length=128), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.import_batch_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('snapshot_date', 'source_file', 'source_sheet', 'source_row', name='uq_portfolio_snapshots_source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
