"""initial schema

Revision ID: fe0848e19929
Revises: 
Create Date: 2026-07-14 13:30:32.933038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0848e19929'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('import_batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('import_batch_id')
    )
    op.create_table('securities',
    sa.Column('security_id', sa.String(length=16), nullable=False),
    sa.Column('portfolio_name', sa.String(length=128), nullable=False),
    sa.Column('canonical_name', sa.String(length=256), nullable=True),
    sa.Column('current_nse_symbol', sa.String(length=32), nullable=True),
    sa.Column('historical_nse_symbol', sa.String(length=32), nullable=True),
    sa.Column('bse_code', sa.String(length=16), nullable=True),
    sa.Column('isin', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('corporate_history', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=128), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('security_id'),
    sa.UniqueConstraint('portfolio_name')
    )
    op.create_table('investment_episodes',
    sa.Column('episode_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.String(length=16), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('total_buy_quantity', sa.Integer(), nullable=False),
    sa.Column('total_sell_quantity', sa.Integer(), nullable=False),
    sa.Column('corporate_action_quantity', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=False),
    sa.Column('final_quantity', sa.Integer(), nullable=False),
    sa.Column('number_of_buys', sa.Integer(), nullable=False),
    sa.Column('number_of_sells', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], ),
    sa.PrimaryKeyConstraint('episode_id')
    )
    op.create_table('liquid_transactions',
    sa.Column('liquid_transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('source_sheet', sa.String(length=128), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('source_key', sa.String(length=768), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.import_batch_id'], ),
    sa.PrimaryKeyConstraint('liquid_transaction_id'),
    sa.UniqueConstraint('source_key', name='uq_liquid_transactions_source_key')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.String(length=16), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('source_sheet', sa.String(length=128), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('source_key', sa.String(length=768), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.import_batch_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('source_key', name='uq_transactions_source_key')
    )
    op.create_table('decision_events',
    sa.Column('decision_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.String(length=16), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('decision_type', sa.String(length=32), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('position_before', sa.Integer(), nullable=False),
    sa.Column('position_after', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['investment_episodes.episode_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], ),
    sa.ForeignKeyConstraint(['source_transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('decision_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_events')
    op.drop_table('transactions')
    op.drop_table('liquid_transactions')
    op.drop_table('investment_episodes')
    op.drop_table('securities')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
